/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab1;

/**
 *
 * @author deleo
 */
public class Loginn extends javax.swing.JFrame {
    public static String passwordSistema = "Rodrigo11."; 
    private int intentos = 0;
    {
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Loginn.class.getName());

    /**
     * Creates new form Loginn
     */
    public Loginn() {
        initComponents();
        this.setLocationRelativeTo(null);
          // Aquí pegas el código para el doble clic
    Access.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
                   if (evt.getClickCount() == 2) {
                    String usuario = Txtuser.getText();
                    String password = new String(jPasswordField1.getPassword());

                    // 1. Validación para Rodrigo (Administrador)
                    if (usuario.equals("Rodrigo") && password.equals(passwordSistema)) {
                        new Menup("Rodrigo").setVisible(true);
                        dispose(); 
                    } 
                    // 2. Validación para Cesarj (Usuario limitado)
                    else if (usuario.equals("Cesarj") && password.equals("Bienvenido11..")) {
                        new Menup("Cesarj").setVisible(true);
                        dispose();
                    } 
                    // 3. Validación para Joser (Usuario limitado)
                    else if (usuario.equals("Joser") && password.equals("Realmadrid21?")) {
                        new Menup("Joser").setVisible(true);
                        dispose();
                    } 
                    // 4. Si fallan las credenciales
                    else {
                        intentos++;
                        int restantes = 3 - intentos;
                        if (intentos >= 3) {
                            javax.swing.JOptionPane.showMessageDialog(null, "Bloqueado: Superaste los 3 intentos.");
                            System.exit(0);
                        } else {
                            javax.swing.JOptionPane.showMessageDialog(null, "Datos incorrectos. Te quedan " + restantes + " intentos.");
                            Txtuser.setText("");
                            jPasswordField1.setText("");
                            Txtuser.requestFocus();
                        }
                    }
                }

        }
    });
    }
private void validarAcceso() {
    String usuario = Txtuser.getText();
    String password = new String(jPasswordField1.getPassword());

    if (usuario.equals("Rodrigo") && password.equals("Rodrigo11.")) {
        new Menup("Rodrigo").setVisible(true);

        this.dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Credenciales incorrectas");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JLabel();
        TxtUser = new javax.swing.JLabel();
        Txtpassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Access = new javax.swing.JButton();
        Txtuser = new javax.swing.JTextField();
        chkShowLogin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Login.setText("Login");

        TxtUser.setText("User");

        Txtpassword.setText("Password");

        Access.setText("Access");
        Access.addActionListener(this::AccessActionPerformed);

        chkShowLogin.addActionListener(this::chkShowLoginActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkShowLogin)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(Access, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Login)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtUser)
                    .addComponent(Txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkShowLogin))
                .addGap(28, 28, 28)
                .addComponent(Access, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessActionPerformed
String usuario = Txtuser.getText();
String password = new String(jPasswordField1.getPassword());

        if (usuario.equals("Rodrigo") && password.equals(passwordSistema)) {
    // Le pasamos el nombre "Rodrigo" al constructor del Menú
    Menup ventanaPrincipal = new Menup("Rodrigo"); 
    ventanaPrincipal.setVisible(true);
    ventanaPrincipal.setLocationRelativeTo(null);
    dispose(); 
} else if (password.equals(passwordSistema)) { 
    // Si entra cualquier otro usuario que no sea Rodrigo
    Menup ventanaPrincipal = new Menup(usuario); 
    ventanaPrincipal.setVisible(true);
    dispose();
}        // TODO add your handling code here:
    }//GEN-LAST:event_AccessActionPerformed

    private void chkShowLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowLoginActionPerformed
                                          
  if (chkShowLogin.isSelected()) {
            // Muestra la contraseña (letras visibles)
            jPasswordField1.setEchoChar((char) 0);
        } else {
            // Oculta la contraseña (vuelve a poner los puntos)
            jPasswordField1.setEchoChar('*');
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_chkShowLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Loginn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Access;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel TxtUser;
    private javax.swing.JLabel Txtpassword;
    private javax.swing.JTextField Txtuser;
    private javax.swing.JCheckBox chkShowLogin;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
